version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nestjs-app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_HOST=db
  #     - DATABASE_PORT=5432
  #     - DATABASE_USER=postgres
  #     - DATABASE_PASSWORD=postgres
  #     - DATABASE_NAME=auth-db
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #   networks:
  #     - nestjs-network

  db:
    image: postgres:16.8-alpine3.20
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: silverio
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth-db
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - nestjs-network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   depends_on:
  #     - db
  #   networks:
  #     - nestjs-network

# networks:
#   nestjs-network:
#     driver: bridge

# volumes:
#   postgres_data:
